### ISSUE TITLE
Gomp freezes upon toggling playback

### ISSUE THREAD

**Issue by oregone1** [aditya-K2/gomp#58] opened 2023-11-16 07:49 UTC
```
λ gomp -v
gomp 1.0.0
Report any issues at: https://github.com/aditya-K2/gomp/issues
```
Upon pressing p, gomp ceases to redraw, but continues to accept keyboard input until it is quit. When it advances to the next song, the album art is redrawn, while the rest of the ui stays static.

**Comment by aditya-K2** [comment] 2023-11-16 11:54
Thanks for reporting this issue. I will take a look.

**Comment by aditya-K2** [comment] 2023-12-23 18:02
https://github.com/aditya-K2/gomp/assets/51816057/4cb4efb7-f622-4d85-8f23-055a478e4dff


Hi! I am unable to recreate this issue. Can you please be more specific? Thanks!

**Comment by oregone1** [comment] 2023-12-23 22:51
https://github.com/aditya-K2/gomp/assets/54779457/2bf3b1d1-82c7-4d85-9b78-4758ef4e4524

Here is an example of the ui freezing. This occurs on multiple builds of ST that I have tested, the recording shows a slightly modified version of https://github.com/Aproxia-dev/st-flexipatch.

**Comment by aditya-K2** [comment] 2024-01-03 07:35
Hi, sorry for the late response but I tried running gomp on my build of st and it seems to work fine. Is it possible for you to provide your build of st? Also, if possible can you please check if this behaviour is happening on other terminal emulators on your system. Thanks.

**Comment by oregone1** [comment] 2024-01-15 22:43
Hi, sorry for the even later response. It does not occur in either xterm or kitty, oddly enough. My st build may be found here. http://0x0.st/HUhN.tar.gz

**Comment by aditya-K2** [comment] 2024-04-18 20:50
Seems like the issue is terminal specific. Closing for now.

**Closed by aditya-K2** 2024-04-18 20:50 UTC
